"""Emit firmware/dashtouch/vectors.h from docs/protocol-vectors.json."""
import json
import pathlib

root = pathlib.Path(__file__).parents[2]
v = json.loads((root / "docs" / "protocol-vectors.json").read_text())


def carr(name, hexstr):
    b = bytes.fromhex(hexstr)
    body = ", ".join(f"0x{x:02x}" for x in b)
    return f"static const uint8_t {name}[{len(b)}] = {{{body}}};"


out = f"""#pragma once
// GENERATED by helper/tools/gen_vectors_header.py — do not edit.
{carr("TV_KEY", v["pairing_key"])}
{carr("TV_NONCE", v["nonce"])}
{carr("TV_HMAC", v["hmac"])}
{carr("TV_RESPONSE_KEY", v["response_key"])}
static const uint32_t TV_COUNTER = {v["counter"]};
static const uint16_t TV_SLOT = {v["slot"]};
static const uint16_t TV_SCORE = {v["score"]};
static const char TV_PW_LINE[] = "{v["pw_line"]}";
static const char TV_PASSWORD[] = "{v["password"]}";
"""
(root / "firmware" / "dashtouch" / "vectors.h").write_text(out)
print("wrote firmware/dashtouch/vectors.h")
